import localFont from "next/font/local";
import '../../styles/globals.css'
import '../../styles/landing.css'
import {NextUIProvider} from "@nextui-org/react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`flex justify-center ${geistSans.variable} ${geistMono.variable} antialiased`}>
      <NextUIProvider className='w-full'>
        {children}
      </NextUIProvider>
      </body>
    </html>
  );
}
